// // "use client"
// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import MiniDrawer from "./Home/Sidebar/page";
// // import { useRouter } from "next/navigation";

// // const inter = Inter({ subsets: ["latin"] });

// // export default function RootLayout({ children }) {
// //   const router = useRouter();
// //   const { pathname } = router;

// //   // Only show MiniDrawer if the current path is not `/login`
// //   const showSidebar = pathname !== '/login';

// //   return (
// //     <html lang="en">
// //       <body className={inter.className}>
// //         {showSidebar ? <MiniDrawer>{children}</MiniDrawer> : children}
// //       </body>
// //     </html>
// //   );
// // }

// // import { Inter } from "next/font/google";
// // import "./globals.css";

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body className={inter.className}>{children}</body>
// //     </html>
// //   );
// // }

// "use client";

// import { useEffect } from 'react';
// import { useRouter } from 'next/navigation';
// import Cookies from 'js-cookie';
// // import MiniDrawer from './Sidebar/page'; // Adjust the import path as needed
// import { Inter } from 'next/font/google';
// import './globals.css';
// import MiniDrawer from './(Home)/Sidebar/page';

// const inter = Inter({ subsets: ['latin'] });

// export default function RootLayout({ children }) {
//   const router = useRouter();

//   useEffect(() => {
//     const token = Cookies.get('Tokensss');
//     const currentPath = router.pathname;

//     if (!token && currentPath !== '/auth') {
//       router.push('/auth');
//     }
//   }, [router]);

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {Cookies.get('Tokensss') ? <MiniDrawer>{children}</MiniDrawer> : children}
//       </body>
//     </html>
//   );
// }


// MainLayout.jsx
"use client";

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
import { Inter } from 'next/font/google';
import './globals.css';
import MiniDrawer from './(Home)/Sidebar/page';

const inter = Inter({ subsets: ['latin'] });

export default function MainLayout({ children }) {
  const router = useRouter();
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    const token = Cookies.get('Tokensss');
    setIsAuthenticated(!!token);
    setIsLoaded(true);

    if (!token && router.pathname !== '/auth') {
      router.push('/auth');
    } else if (token && router.pathname === '/auth') {
      router.push('/');
    }
  }, [router]);

  if (!isLoaded) {
    return null; // or a loading spinner
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        {isAuthenticated && children } 
        {/* {isAuthenticated ? <MiniDrawer>{children}</MiniDrawer> : children} */}
      </body>
    </html>
  );
}
